add banner file structure
furtive-falcons/catwalk-website-react pull request #25
Opened 2021-02-26 22:03 UTC by melliottgithub

added banner components and structure

2021-02-26 22:20 UTC, kevinalexliu requested changes
Need to fix the conflicts. i didn't see anything in the _test_ file, so I guess that is why circleCI is not working.

2021-02-26 22:37 UTC, jackzhen1996 approved these changes

2021-02-26 23:29 UTC, Smrosner approved these changes
looks great, nice frag

2021-02-27 00:02 UTC, kevinalexliu approved these changes

2021-02-27 01:42 UTC, closed without merging